apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "apim-320-dist-oke.resource.prefix" . }}-am-km-log-storage-volume
  namespace : {{ .Release.Namespace }}
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.wso2.deployment.storage.mountTargetIP }}
    path: "/{{ template "apim-320-dist-oke.resource.prefix" . }}-km-volume/am-km-log-storage-volume"