apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "apim-320-dist-oke.resource.prefix" . }}-am-km-log-storage-volume-claim
  namespace : {{ .Release.Namespace }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: {{ template "apim-320-dist-oke.resource.prefix" . }}-am-km-log-storage-volume