apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "apim-320-dist-oke.resource.prefix" . }}-db-mysql-storage
  namespace : {{ .Release.Namespace }}
  labels:
    deployment: wso2am-mysql
    product: api-manager
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.wso2.deployment.storage.mountTargetIP }}
    path: "/{{ template "apim-320-dist-oke.resource.prefix" . }}-db-volume/mysql-data-store"