
apiVersion: v1
kind: Service
metadata:
  name: {{ template "apim-320-dist-oke.resource.prefix" . }}-mysql-service
  namespace : {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    deployment: wso2am-mysql
    product: api-manager
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306
      protocol: TCP
---
