apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "apim-320-dist-oke.resource.prefix" . }}-db-mysql-storage-volume-claim
  namespace : {{ .Release.Namespace }}
  labels:
    deployment: wso2am-mysql
    product: api-manager
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: {{ template "apim-320-dist-oke.resource.prefix" . }}-db-mysql-storage