apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "apim-320-dist-oke.resource.prefix" . }}-am-tm-shared-executionplans-volume
  namespace : {{ .Release.Namespace }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.wso2.deployment.storage.mountTargetIP }}
    path: "/{{ template "apim-320-dist-oke.resource.prefix" . }}-tm-volume/am-tm-shared-executionplans-volume"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "apim-320-dist-oke.resource.prefix" . }}-am-tm-log-storage-volume
  namespace : {{ .Release.Namespace }}
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.wso2.deployment.storage.mountTargetIP }}
    path: "/{{ template "apim-320-dist-oke.resource.prefix" . }}-tm-volume/am-tm-log-storage-volume"
