apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "apim-320-dist-oke.resource.prefix" . }}-am-analytics-worker-log-storage-volume
  namespace : {{ .Release.Namespace }}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.wso2.deployment.storage.mountTargetIP }}
    path: "/{{ template "apim-320-dist-oke.resource.prefix" . }}-ana-worker-volume/am-analytics-worker-log-storage-volume"
